# Generated by Django 2.0.2 on 2018-03-02 06:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100)),
                ('categorydetails', models.TextField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=100)),
                ('createdate', models.DateTimeField(verbose_name='Create Date')),
                ('active', models.BooleanField(default=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('approve', models.CharField(max_length=4)),
                ('description', models.CharField(max_length=500)),
                ('commentid', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=200)),
                ('line', models.CharField(max_length=20)),
                ('web', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('hashtag', models.TextField()),
                ('bcapprove', models.TextField()),
                ('posterpic', models.TextField()),
                ('createdate', models.DateTimeField(verbose_name='Create Date')),
                ('updatedate', models.DateTimeField(verbose_name='Editdate Date')),
                ('startdate', models.DateTimeField(verbose_name='Start Date')),
                ('enddate', models.DateTimeField(verbose_name='End Date')),
                ('active', models.BooleanField(default=True)),
                ('limited', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='createby',
            field=models.ManyToManyField(to='tugether.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='createby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugether.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='eventid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugether.Event'),
        ),
        migrations.AddField(
            model_name='category',
            name='createby',
            field=models.ManyToManyField(to='tugether.User'),
        ),
        migrations.AddField(
            model_name='category',
            name='eventid',
            field=models.ManyToManyField(to='tugether.Event'),
        ),
    ]
