# Generated by Django 2.0.4 on 2018-04-08 04:15

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='createby',
            new_name='userid',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='major',
        ),
        migrations.RemoveField(
            model_name='event',
            name='commentid',
        ),
        migrations.AddField(
            model_name='event',
            name='eventenddate',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='Event End Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='eventstdate',
            field=models.DateTimeField(default=django.utils.datetime_safe.date.today, verbose_name='Event Start Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='join',
            field=models.ManyToManyField(to='tugether.User'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='createby',
        ),
        migrations.AddField(
            model_name='event',
            name='createby',
            field=models.IntegerField(default=0),
        ),
    ]
