# Generated by Django 2.0.4 on 2018-04-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='eventid',
        ),
        migrations.RemoveField(
            model_name='category',
            name='userid',
        ),
        migrations.AddField(
            model_name='event',
            name='categoryid',
            field=models.ManyToManyField(to='tugether.Category'),
        ),
        migrations.AddField(
            model_name='user',
            name='categoryid',
            field=models.ManyToManyField(to='tugether.Category'),
        ),
        migrations.AlterField(
            model_name='event',
            name='join',
            field=models.ManyToManyField(default=[], to='tugether.User'),
        ),
    ]
