# Generated by Django 2.0.4 on 2018-05-07 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0002_auto_20180418_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.TextField()),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugether.User')),
            ],
        ),
    ]
