# Generated by Django 2.0.4 on 2018-05-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0005_auto_20180510_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bcapprove',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='categoryid',
            field=models.ManyToManyField(default=[], to='tugether.Category'),
        ),
    ]
