# Generated by Django 2.0.4 on 2018-05-11 03:43

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0007_auto_20180510_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userpic',
            field=models.TextField(default=django.utils.datetime_safe.date.today),
            preserve_default=False,
        ),
    ]
