# Generated by Django 2.0 on 2018-05-22 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0008_user_userpic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categoryid',
        ),
        migrations.AlterField(
            model_name='comment',
            name='createby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='join',
            field=models.ManyToManyField(default=[], to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='noti',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
