# Generated by Django 2.0 on 2018-05-26 07:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tugether', '0009_auto_20180522_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('nation', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
                ('year', models.CharField(max_length=1)),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('active', models.BooleanField(default=True)),
                ('userpic', models.TextField()),
                ('categoryid', models.ManyToManyField(to='tugether.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='createby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugether.User'),
        ),
        migrations.AlterField(
            model_name='event',
            name='join',
            field=models.ManyToManyField(default=[], to='tugether.User'),
        ),
        migrations.AlterField(
            model_name='noti',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tugether.User'),
        ),
    ]
